/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "cfrkzguhalhkqfifgghj"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNmcmt6Z3VoYWxoa3FmaWZnZ2hqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMjQwNDcsImV4cCI6MjA3MjkwMDA0N30.Tmc-PiWT3KtO_grNPceG-lutU7Exv11qwdzZrb9dNRo"